services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - deploy_network
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data
    depends_on:
      - mongodb
  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data
networks:
  deploy_network:
    driver: bridge
volumes:
  mis_datos:
